// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9LghAiHXbPbeSKCFQroP1-MU1-NTmE6Y',
    appId: '1:504972603200:web:f41707f4d1a093f2f3d4a5',
    messagingSenderId: '504972603200',
    projectId: 'lipiddiary',
    authDomain: 'lipiddiary.firebaseapp.com',
    databaseURL: 'https://lipiddiary-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lipiddiary.appspot.com',
    measurementId: 'G-579MQ2GKKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB55RebqxbskOLysM9URQQRAcvpCzdll-0',
    appId: '1:504972603200:android:3c6cec4015d2091af3d4a5',
    messagingSenderId: '504972603200',
    projectId: 'lipiddiary',
    databaseURL: 'https://lipiddiary-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lipiddiary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcWSje7wj9tVfJ9Mv1NMqxO_ccSwTziP4',
    appId: '1:504972603200:ios:43e2830aab558e48f3d4a5',
    messagingSenderId: '504972603200',
    projectId: 'lipiddiary',
    databaseURL: 'https://lipiddiary-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lipiddiary.appspot.com',
    androidClientId: '504972603200-itkpkgj9cjng939gss31cvj76jtnvjpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.colipid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcWSje7wj9tVfJ9Mv1NMqxO_ccSwTziP4',
    appId: '1:504972603200:ios:43e2830aab558e48f3d4a5',
    messagingSenderId: '504972603200',
    projectId: 'lipiddiary',
    databaseURL: 'https://lipiddiary-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lipiddiary.appspot.com',
    androidClientId: '504972603200-itkpkgj9cjng939gss31cvj76jtnvjpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.colipid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9LghAiHXbPbeSKCFQroP1-MU1-NTmE6Y',
    appId: '1:504972603200:web:12b3481308709afbf3d4a5',
    messagingSenderId: '504972603200',
    projectId: 'lipiddiary',
    authDomain: 'lipiddiary.firebaseapp.com',
    databaseURL: 'https://lipiddiary-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lipiddiary.appspot.com',
    measurementId: 'G-QMKSCPE6TG',
  );
}
